force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <description>Object to link a candidate to a position</description>
    <label>Application</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Application__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The position related to the application sent</description>
    <label>Position</label>
    <referenceTo>Position__c</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application__c/recordTypes/Application.recordType-meta.xml
<RecordType>
    <fullName>Application</fullName>
    <active>true</active>
    <description>Default Application Record Type</description>
    <label>Application</label>
</RecordType>

force-app/main/default/objects/Position__c/Position__c.object-meta.xml
<CustomObject>
    <label>Position</label>
    <nameField>
        <label>Position Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Position__c/fields/Number_of_Applications__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Applications__c</fullName>
    <label>Number of Applications</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/Applications.cls
public inherited sharing class Applications extends ObjDomain {
    public Applications(Application__c[] sObjectList){
        super(sObjectList);
    }
    public Applications(Application__c[] sObjectList, Map<Id, Application__c> sObjectMap){
        super(sObjectList,sObjectMap);
    }
    
    public void numberOfApplications(){
        //Retrieve the list of positions and predefine a total of zero
        Map<Id,Integer> myMap=new Map<Id,Integer>();
        for(Application__c Application:(Application__c[])Records){
            myMap.put(Application.Position__c,0);
        }
        //Count the children if any
        for(AggregateResult ar:[Select count(Id) sum, Position__c from Application__c where Position__c in:myMap.keySet() group By Position__c]) {
            myMap.put((Id)ar.get('Position__c'),(Integer)ar.get('sum'));
        }
        //Prepare the list of records to update
        Position__c[] Pos=new Position__c[]{};
        for(Id i:myMap.keySet()){
            Pos.add(new Position__c(Id=i,Number_of_Applications__c=myMap.get(i)));
        }
        Update Pos;
    }    
    
}